// accountActions

export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'

export const SET_STATE_ACCOUNTS = 'SET_STATE_ACCOUNTS'

// networkActions

export const CONNECT_NETWORK = 'CONNECT_NETWORK'
export const CONNECT_NETWORK_ERROR = 'CONNECT_NETWORK_ERROR'
export const CONNECT_NETWORK_SUCCESS = 'CONNECT_NETWORK_SUCCESS'

export const SET_STATE_NETWORK_CLIENT = 'SET_STATE_NETWORK_CLIENT'
