/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface TokenLockingInterface extends Interface {
  functions: {
    authority: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    setAuthority: TypedFunctionDescription<{
      encode([authority_]: [string]): string;
    }>;

    setOwner: TypedFunctionDescription<{ encode([owner_]: [string]): string }>;

    setColonyNetwork: TypedFunctionDescription<{
      encode([_colonyNetwork]: [string]): string;
    }>;

    getColonyNetwork: TypedFunctionDescription<{ encode([]: []): string }>;

    lockToken: TypedFunctionDescription<{ encode([_token]: [string]): string }>;

    unlockTokenForUser: TypedFunctionDescription<{
      encode([_token, _user, _lockId]: [string, string, BigNumberish]): string;
    }>;

    incrementLockCounterTo: TypedFunctionDescription<{
      encode([_token, _lockId]: [string, BigNumberish]): string;
    }>;

    deposit: TypedFunctionDescription<{
      encode([_token, _amount]: [string, BigNumberish]): string;
    }>;

    depositFor: TypedFunctionDescription<{
      encode([_token, _amount, _recipient]: [
        string,
        BigNumberish,
        string
      ]): string;
    }>;

    claim: TypedFunctionDescription<{
      encode([_token, _force]: [string, boolean]): string;
    }>;

    transfer: TypedFunctionDescription<{
      encode([_token, _amount, _recipient, _force]: [
        string,
        BigNumberish,
        string,
        boolean
      ]): string;
    }>;

    withdraw: TypedFunctionDescription<{
      encode([_token, _amount, _force]: [
        string,
        BigNumberish,
        boolean
      ]): string;
    }>;

    approveStake: TypedFunctionDescription<{
      encode([_user, _amount, _token]: [string, BigNumberish, string]): string;
    }>;

    obligateStake: TypedFunctionDescription<{
      encode([_user, _amount, _token]: [string, BigNumberish, string]): string;
    }>;

    deobligateStake: TypedFunctionDescription<{
      encode([_user, _amount, _token]: [string, BigNumberish, string]): string;
    }>;

    transferStake: TypedFunctionDescription<{
      encode([_user, _amount, _token, _recipient]: [
        string,
        BigNumberish,
        string,
        string
      ]): string;
    }>;

    reward: TypedFunctionDescription<{
      encode([_recipient, _amount]: [string, BigNumberish]): string;
    }>;

    burn: TypedFunctionDescription<{
      encode([_amount]: [BigNumberish]): string;
    }>;

    getTotalLockCount: TypedFunctionDescription<{
      encode([_token]: [string]): string;
    }>;

    getUserLock: TypedFunctionDescription<{
      encode([_token, _user]: [string, string]): string;
    }>;

    getTotalObligation: TypedFunctionDescription<{
      encode([_user, _token]: [string, string]): string;
    }>;

    getApproval: TypedFunctionDescription<{
      encode([_user, _token, _obligator]: [string, string, string]): string;
    }>;

    getObligation: TypedFunctionDescription<{
      encode([_user, _token, _obligator]: [string, string, string]): string;
    }>;
  };

  events: {
    ColonyNetworkSet: TypedEventDescription<{
      encodeTopics([colonyNetwork]: [null]): string[];
    }>;

    LogSetAuthority: TypedEventDescription<{
      encodeTopics([authority]: [string | null]): string[];
    }>;

    LogSetOwner: TypedEventDescription<{
      encodeTopics([owner]: [string | null]): string[];
    }>;

    TokenLocked: TypedEventDescription<{
      encodeTopics([token, lockCount]: [null, null]): string[];
    }>;

    UserTokenClaimed: TypedEventDescription<{
      encodeTopics([token, user, amount]: [null, null, null]): string[];
    }>;

    UserTokenDeposited: TypedEventDescription<{
      encodeTopics([token, user, amount]: [null, null, null]): string[];
    }>;

    UserTokenTransferred: TypedEventDescription<{
      encodeTopics([token, user, recipient, amount]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    UserTokenUnlocked: TypedEventDescription<{
      encodeTopics([token, user, lockId]: [null, null, null]): string[];
    }>;

    UserTokenWithdrawn: TypedEventDescription<{
      encodeTopics([token, user, amount]: [null, null, null]): string[];
    }>;
  };
}

export class TokenLocking extends Contract {
  connect(signerOrProvider: Signer | Provider | string): TokenLocking;
  attach(addressOrName: string): TokenLocking;
  deployed(): Promise<TokenLocking>;

  on(event: EventFilter | string, listener: Listener): TokenLocking;
  once(event: EventFilter | string, listener: Listener): TokenLocking;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): TokenLocking;
  removeAllListeners(eventName: EventFilter | string): TokenLocking;
  removeListener(eventName: any, listener: Listener): TokenLocking;

  interface: TokenLockingInterface;

  functions: {
    authority(): Promise<string>;

    owner(): Promise<string>;

    setAuthority(
      authority_: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setOwner(
      owner_: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setColonyNetwork(
      _colonyNetwork: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getColonyNetwork(): Promise<string>;

    lockToken(
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    unlockTokenForUser(
      _token: string,
      _user: string,
      _lockId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    incrementLockCounterTo(
      _token: string,
      _lockId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deposit(
      _token: string,
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    depositFor(
      _token: string,
      _amount: BigNumberish,
      _recipient: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    claim(
      _token: string,
      _force: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transfer(
      _token: string,
      _amount: BigNumberish,
      _recipient: string,
      _force: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "withdraw(address,uint256,bool)"(
      _token: string,
      _amount: BigNumberish,
      _force: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "withdraw(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    approveStake(
      _user: string,
      _amount: BigNumberish,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    obligateStake(
      _user: string,
      _amount: BigNumberish,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deobligateStake(
      _user: string,
      _amount: BigNumberish,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferStake(
      _user: string,
      _amount: BigNumberish,
      _token: string,
      _recipient: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    reward(_recipient: string, _amount: BigNumberish): Promise<void>;

    burn(
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getTotalLockCount(_token: string): Promise<BigNumber>;

    getUserLock(
      _token: string,
      _user: string
    ): Promise<{
      lockCount: BigNumber;
      balance: BigNumber;
      DEPRECATED_timestamp: BigNumber;
      pendingBalance: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
    }>;

    getTotalObligation(_user: string, _token: string): Promise<BigNumber>;

    getApproval(
      _user: string,
      _token: string,
      _obligator: string
    ): Promise<BigNumber>;

    getObligation(
      _user: string,
      _token: string,
      _obligator: string
    ): Promise<BigNumber>;
  };

  authority(): Promise<string>;

  owner(): Promise<string>;

  setAuthority(
    authority_: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setOwner(
    owner_: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setColonyNetwork(
    _colonyNetwork: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getColonyNetwork(): Promise<string>;

  lockToken(
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  unlockTokenForUser(
    _token: string,
    _user: string,
    _lockId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  incrementLockCounterTo(
    _token: string,
    _lockId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  deposit(
    _token: string,
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  depositFor(
    _token: string,
    _amount: BigNumberish,
    _recipient: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  claim(
    _token: string,
    _force: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transfer(
    _token: string,
    _amount: BigNumberish,
    _recipient: string,
    _force: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "withdraw(address,uint256,bool)"(
    _token: string,
    _amount: BigNumberish,
    _force: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "withdraw(address,uint256)"(
    _token: string,
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  approveStake(
    _user: string,
    _amount: BigNumberish,
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  obligateStake(
    _user: string,
    _amount: BigNumberish,
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  deobligateStake(
    _user: string,
    _amount: BigNumberish,
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferStake(
    _user: string,
    _amount: BigNumberish,
    _token: string,
    _recipient: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  reward(_recipient: string, _amount: BigNumberish): Promise<void>;

  burn(
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getTotalLockCount(_token: string): Promise<BigNumber>;

  getUserLock(
    _token: string,
    _user: string
  ): Promise<{
    lockCount: BigNumber;
    balance: BigNumber;
    DEPRECATED_timestamp: BigNumber;
    pendingBalance: BigNumber;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
  }>;

  getTotalObligation(_user: string, _token: string): Promise<BigNumber>;

  getApproval(
    _user: string,
    _token: string,
    _obligator: string
  ): Promise<BigNumber>;

  getObligation(
    _user: string,
    _token: string,
    _obligator: string
  ): Promise<BigNumber>;

  filters: {
    ColonyNetworkSet(colonyNetwork: null): EventFilter;

    LogSetAuthority(authority: string | null): EventFilter;

    LogSetOwner(owner: string | null): EventFilter;

    TokenLocked(token: null, lockCount: null): EventFilter;

    UserTokenClaimed(token: null, user: null, amount: null): EventFilter;

    UserTokenDeposited(token: null, user: null, amount: null): EventFilter;

    UserTokenTransferred(
      token: null,
      user: null,
      recipient: null,
      amount: null
    ): EventFilter;

    UserTokenUnlocked(token: null, user: null, lockId: null): EventFilter;

    UserTokenWithdrawn(token: null, user: null, amount: null): EventFilter;
  };

  estimate: {
    authority(): Promise<BigNumber>;

    owner(): Promise<BigNumber>;

    setAuthority(authority_: string): Promise<BigNumber>;

    setOwner(owner_: string): Promise<BigNumber>;

    setColonyNetwork(_colonyNetwork: string): Promise<BigNumber>;

    getColonyNetwork(): Promise<BigNumber>;

    lockToken(_token: string): Promise<BigNumber>;

    unlockTokenForUser(
      _token: string,
      _user: string,
      _lockId: BigNumberish
    ): Promise<BigNumber>;

    incrementLockCounterTo(
      _token: string,
      _lockId: BigNumberish
    ): Promise<BigNumber>;

    deposit(_token: string, _amount: BigNumberish): Promise<BigNumber>;

    depositFor(
      _token: string,
      _amount: BigNumberish,
      _recipient: string
    ): Promise<BigNumber>;

    claim(_token: string, _force: boolean): Promise<BigNumber>;

    transfer(
      _token: string,
      _amount: BigNumberish,
      _recipient: string,
      _force: boolean
    ): Promise<BigNumber>;

    withdraw(
      _token: string,
      _amount: BigNumberish,
      _force: boolean
    ): Promise<BigNumber>;

    approveStake(
      _user: string,
      _amount: BigNumberish,
      _token: string
    ): Promise<BigNumber>;

    obligateStake(
      _user: string,
      _amount: BigNumberish,
      _token: string
    ): Promise<BigNumber>;

    deobligateStake(
      _user: string,
      _amount: BigNumberish,
      _token: string
    ): Promise<BigNumber>;

    transferStake(
      _user: string,
      _amount: BigNumberish,
      _token: string,
      _recipient: string
    ): Promise<BigNumber>;

    reward(_recipient: string, _amount: BigNumberish): Promise<BigNumber>;

    burn(_amount: BigNumberish): Promise<BigNumber>;

    getTotalLockCount(_token: string): Promise<BigNumber>;

    getUserLock(_token: string, _user: string): Promise<BigNumber>;

    getTotalObligation(_user: string, _token: string): Promise<BigNumber>;

    getApproval(
      _user: string,
      _token: string,
      _obligator: string
    ): Promise<BigNumber>;

    getObligation(
      _user: string,
      _token: string,
      _obligator: string
    ): Promise<BigNumber>;
  };
}
