// accountActions

export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'

export const SET_STATE_ACCOUNTS = 'SET_STATE_ACCOUNTS'

// authorityActions

export const ADD_ADMIN = 'ADD_ADMIN'
export const ADD_ADMIN_ERROR = 'ADD_ADMIN_ERROR'
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS'

export const CHECK_ADMIN = 'CHECK_ADMIN'
export const CHECK_ADMIN_ERROR = 'CHECK_ADMIN_ERROR'
export const CHECK_ADMIN_SUCCESS = 'CHECK_ADMIN_SUCCESS'

export const REMOVE_ADMIN = 'REMOVE_ADMIN'
export const REMOVE_ADMIN_ERROR = 'REMOVE_ADMIN_ERROR'
export const REMOVE_ADMIN_SUCCESS = 'REMOVE_ADMIN_SUCCESS'

export const SET_STATE_ADMIN = 'SET_STATE_ADMIN'

// colonyActions

export const CREATE_COLONY = 'CREATE_COLONY'
export const CREATE_COLONY_ERROR = 'CREATE_COLONY_ERROR'
export const CREATE_COLONY_SUCCESS = 'CREATE_COLONY_SUCCESS'

export const GET_COLONY_CLIENT = 'GET_COLONY_CLIENT'
export const GET_COLONY_CLIENT_ERROR = 'GET_COLONY_CLIENT_ERROR'
export const GET_COLONY_CLIENT_SUCCESS = 'GET_COLONY_CLIENT_SUCCESS'

export const SET_STATE_COLONY_CLIENT = 'SET_STATE_COLONY_CLIENT'

// domainActions

export const ADD_DOMAIN = 'ADD_DOMAIN'
export const ADD_DOMAIN_ERROR = 'ADD_DOMAIN_ERROR'
export const ADD_DOMAIN_SUCCESS = 'ADD_DOMAIN_SUCCESS'

export const FUND_DOMAIN = 'FUND_DOMAIN'
export const FUND_DOMAIN_ERROR = 'FUND_DOMAIN_ERROR'
export const FUND_DOMAIN_SUCCESS = 'FUND_DOMAIN_SUCCESS'

export const GET_DOMAINS = 'GET_DOMAINS'
export const GET_DOMAINS_ERROR = 'GET_DOMAINS_ERROR'
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS'

export const SET_STATE_DOMAINS = 'SET_STATE_DOMAINS'

// networkActions

export const CONNECT_NETWORK = 'CONNECT_NETWORK'
export const CONNECT_NETWORK_ERROR = 'CONNECT_NETWORK_ERROR'
export const CONNECT_NETWORK_SUCCESS = 'CONNECT_NETWORK_SUCCESS'

export const SET_STATE_NETWORK_CLIENT = 'SET_STATE_NETWORK_CLIENT'

// fundingActions

export const CLAIM_FUNDS = 'CLAIM_FUNDS'
export const CLAIM_FUNDS_ERROR = 'CLAIM_FUNDS_ERROR'
export const CLAIM_FUNDS_SUCCESS = 'CLAIM_FUNDS_SUCCESS'

export const MOVE_FUNDS = 'MOVE_FUNDS'
export const MOVE_FUNDS_ERROR = 'MOVE_FUNDS_ERROR'
export const MOVE_FUNDS_SUCCESS = 'MOVE_FUNDS_SUCCESS'

export const GET_CLAIMABLE_FUNDS = 'GET_CLAIMABLE_FUNDS'
export const GET_CLAIMABLE_FUNDS_ERROR = 'GET_CLAIMABLE_FUNDS_ERROR'
export const GET_CLAIMABLE_FUNDS_SUCCESS = 'GET_CLAIMABLE_FUNDS_SUCCESS'

export const GET_POTS = 'GET_POTS'
export const GET_POTS_ERROR = 'GET_POTS_ERROR'
export const GET_POTS_SUCCESS = 'GET_POTS_SUCCESS'

export const SET_STATE_CLAIMABLE_FUNDS = 'SET_STATE_CLAIMABLE_FUNDS'
export const SET_STATE_POTS = 'SET_STATE_POTS'

// networkActions

export const GET_SKILLS = 'GET_SKILLS'
export const GET_SKILLS_ERROR = 'GET_SKILLS_ERROR'
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS'

export const SET_STATE_SKILLS = 'SET_STATE_SKILLS'

// taskActions

export const CANCEL_TASK = 'CANCEL_TASK'
export const CANCEL_TASK_ERROR = 'CANCEL_TASK_ERROR'
export const CANCEL_TASK_SUCCESS = 'CANCEL_TASK_SUCCESS'

export const CLAIM_PAYOUT = 'CLAIM_PAYOUT'
export const CLAIM_PAYOUT_ERROR = 'CLAIM_PAYOUT_ERROR'
export const CLAIM_PAYOUT_SUCCESS = 'CLAIM_PAYOUT_SUCCESS'

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'

export const FINALIZE_TASK = 'FINALIZE_TASK'
export const FINALIZE_TASK_ERROR = 'FINALIZE_TASK_ERROR'
export const FINALIZE_TASK_SUCCESS = 'FINALIZE_TASK_SUCCESS'

export const FUND_TASK = 'FUND_TASK'
export const FUND_TASK_ERROR = 'FUND_TASK_ERROR'
export const FUND_TASK_SUCCESS = 'FUND_TASK_SUCCESS'

export const GET_MULTISIG_OPERATIONS = 'GET_MULTISIG_OPERATIONS'
export const GET_MULTISIG_OPERATIONS_ERROR = 'GET_MULTISIG_OPERATIONS_ERROR'
export const GET_MULTISIG_OPERATIONS_SUCCESS = 'GET_MULTISIG_OPERATIONS_SUCCESS'

export const GET_TASK = 'GET_TASK'
export const GET_TASK_ERROR = 'GET_TASK_ERROR'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'

export const GET_TASKS = 'GET_TASKS'
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

export const REMOVE_TASK_ROLE = 'REMOVE_TASK_ROLE'
export const REMOVE_TASK_ROLE_ERROR = 'REMOVE_TASK_ROLE_ERROR'
export const REMOVE_TASK_ROLE_SUCCESS = 'REMOVE_TASK_ROLE_SUCCESS'

export const REVEAL_RATING = 'REVEAL_RATING'
export const REVEAL_RATING_ERROR = 'REVEAL_RATING_ERROR'
export const REVEAL_RATING_SUCCESS = 'REVEAL_RATING_SUCCESS'

export const SET_STATE_MULTISIG_OPERATIONS = 'SET_STATE_MULTISIG_OPERATIONS'
export const SET_STATE_TASK = 'SET_STATE_TASK'
export const SET_STATE_TASK_COUNT = 'SET_STATE_TASK_COUNT'
export const SET_STATE_TASKS = 'SET_STATE_TASKS'

export const SET_TASK_DETAILS = 'SET_TASK_DETAILS'
export const SET_TASK_DETAILS_ERROR = 'SET_TASK_DETAILS_ERROR'
export const SET_TASK_DETAILS_SUCCESS = 'SET_TASK_DETAILS_SUCCESS'

export const SET_TASK_PAYOUTS = 'SET_TASK_PAYOUTS'
export const SET_TASK_PAYOUTS_ERROR = 'SET_TASK_PAYOUTS_ERROR'
export const SET_TASK_PAYOUTS_SUCCESS = 'SET_TASK_PAYOUTS_SUCCESS'

export const SET_TASK_ROLE = 'SET_TASK_ROLE'
export const SET_TASK_ROLE_ERROR = 'SET_TASK_ROLE_ERROR'
export const SET_TASK_ROLE_SUCCESS = 'SET_TASK_ROLE_SUCCESS'

export const SIGN_TASK = 'SIGN_TASK'
export const SIGN_TASK_ERROR = 'SIGN_TASK_ERROR'
export const SIGN_TASK_SUCCESS = 'SIGN_TASK_SUCCESS'

export const SUBMIT_RATING = 'SUBMIT_RATING'
export const SUBMIT_RATING_ERROR = 'SUBMIT_RATING_ERROR'
export const SUBMIT_RATING_SUCCESS = 'SUBMIT_RATING_SUCCESS'

export const SUBMIT_WORK = 'SUBMIT_WORK'
export const SUBMIT_WORK_ERROR = 'SUBMIT_WORK_ERROR'
export const SUBMIT_WORK_SUCCESS = 'SUBMIT_WORK_SUCCESS'

// tokenActions

export const CREATE_TOKEN = 'CREATE_TOKEN'
export const CREATE_TOKEN_ERROR = 'CREATE_TOKEN_ERROR'
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS'

export const GET_TOKEN = 'GET_TOKEN'
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

export const MINT_TOKENS = 'MINT_TOKENS'
export const MINT_TOKENS_ERROR = 'MINT_TOKENS_ERROR'
export const MINT_TOKENS_SUCCESS = 'MINT_TOKENS_SUCCESS'

export const SET_STATE_TOKEN = 'SET_STATE_TOKEN'
export const SET_STATE_TOKEN_ADDRESS = 'SET_STATE_TOKEN_ADDRESS'
