/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OneTxPayment } from "./OneTxPayment";
export * as factories from "./factories";
export { OneTxPayment__factory } from "./factories/OneTxPayment__factory";
